// <auto-generated />
using System;
using BancoDigital.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace BancoDigital.Api.Data.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20260505225548_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BancoDigital.Api.Domain.Entities.Agencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_AGENCIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("NR_CODIGO");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_ENDERECO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_AGENCIA");

                    b.HasKey("Id");

                    b.ToTable("TB_AGENCIA", (string)null);
                });

            modelBuilder.Entity("BancoDigital.Api.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLIENTE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AgenciaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_AGENCIA");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_NOME");

                    b.Property<string>("TP_CLIENTE")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("DS_TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.ToTable("TB_CLIENTE", (string)null);

                    b.HasDiscriminator<string>("TP_CLIENTE").HasValue("Cliente");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BancoDigital.Api.Domain.Entities.Contratacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CONTRATACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLIENTE");

                    b.Property<DateTime?>("DataProcessamento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_PROCESSAMENTO");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_SOLICITACAO");

                    b.Property<string>("ObservacaoProcessamento")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DS_OBSERVACAO");

                    b.Property<long>("ProdutoId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PRODUTO");

                    b.Property<int>("ScoreCredito")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_SCORE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TP_STATUS");

                    b.Property<decimal>("ValorSolicitado")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("VL_SOLICITADO");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("TB_CONTRATACAO", (string)null);
                });

            modelBuilder.Entity("BancoDigital.Api.Domain.Entities.Produto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PRODUTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_PRODUTO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_PRODUTO");

                    b.Property<string>("TP_PRODUTO")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("NVARCHAR2(21)");

                    b.HasKey("Id");

                    b.ToTable("TB_PRODUTO", (string)null);

                    b.HasDiscriminator<string>("TP_PRODUTO").HasValue("Produto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BancoDigital.Api.Domain.Entities.PessoaFisica", b =>
                {
                    b.HasBaseType("BancoDigital.Api.Domain.Entities.Cliente");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)")
                        .HasColumnName("NR_CPF");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_NASCIMENTO");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("\"NR_CPF\" IS NOT NULL");

                    b.HasDiscriminator().HasValue("PF");
                });

            modelBuilder.Entity("BancoDigital.Api.Domain.Entities.PessoaJuridica", b =>
                {
                    b.HasBaseType("BancoDigital.Api.Domain.Entities.Cliente");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("NR_CNPJ");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("DS_RAZAO_SOCIAL");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasFilter("\"NR_CNPJ\" IS NOT NULL");

                    b.HasDiscriminator().HasValue("PJ");
                });

            modelBuilder.Entity("BancoDigital.Api.Domain.Entities.Emprestimo", b =>
                {
                    b.HasBaseType("BancoDigital.Api.Domain.Entities.Produto");

                    b.Property<decimal>("TaxaJurosMensal")
                        .HasColumnType("NUMBER(5,4)")
                        .HasColumnName("PC_TAXA_JUROS");

                    b.Property<decimal>("ValorMaximo")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("VL_MAXIMO");

                    b.Property<decimal>("ValorMinimo")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("VL_MINIMO");

                    b.HasDiscriminator().HasValue("EMPRESTIMO");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Descricao = "Empréstimo pessoal com análise de crédito automatizada",
                            Nome = "Empréstimo Pessoal",
                            TaxaJurosMensal = 0.0299m,
                            ValorMaximo = 50000m,
                            ValorMinimo = 1000m
                        });
                });

            modelBuilder.Entity("BancoDigital.Api.Domain.Entities.MaquinaDeCartao", b =>
                {
                    b.HasBaseType("BancoDigital.Api.Domain.Entities.Produto");

                    b.Property<decimal>("TaxaMdr")
                        .HasColumnType("NUMBER(5,4)")
                        .HasColumnName("PC_TAXA_MDR");

                    b.HasDiscriminator().HasValue("MAQUINA_CARTAO");
                });

            modelBuilder.Entity("BancoDigital.Api.Domain.Entities.ReceberSalario", b =>
                {
                    b.HasBaseType("BancoDigital.Api.Domain.Entities.Produto");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("NM_EMPRESA");

                    b.HasDiscriminator().HasValue("RECEBER_SALARIO");
                });

            modelBuilder.Entity("BancoDigital.Api.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("BancoDigital.Api.Domain.Entities.Agencia", "Agencia")
                        .WithMany("Clientes")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("BancoDigital.Api.Domain.Entities.Contratacao", b =>
                {
                    b.HasOne("BancoDigital.Api.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Contratacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancoDigital.Api.Domain.Entities.Produto", "Produto")
                        .WithMany("Contratacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BancoDigital.Api.Domain.Entities.Agencia", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("BancoDigital.Api.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Contratacoes");
                });

            modelBuilder.Entity("BancoDigital.Api.Domain.Entities.Produto", b =>
                {
                    b.Navigation("Contratacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
